// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdgsxomrhbwevupgqvob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkZ3N4b21yaGJ3ZXZ1cGdxdm9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTE5NTUsImV4cCI6MjA3Mzc4Nzk1NX0.8qC072shGZa3yVW3QnnfT3ku2CEyk9AboyeY92Q5eFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});